# Generated by Django 4.2 on 2023-07-24 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Категория')),
                ('summa', models.IntegerField(blank=True, null=True, verbose_name='cумма')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Категория')),
                ('summa', models.IntegerField(blank=True, null=True, verbose_name='cумма')),
            ],
            options={
                'verbose_name': 'Категория для графика',
                'verbose_name_plural': 'Категория для графика',
            },
        ),
        migrations.CreateModel(
            name='Category5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Выполнено')),
            ],
        ),
        migrations.CreateModel(
            name='Complete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cvartals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('1 квартал', '1 квартал'), ('2 квартал', '2 квартал'), ('3 квартал', '3 квартал'), ('4 квартал', '4 квартал')], db_index=True, max_length=100, null=True, verbose_name='Квартал')),
            ],
        ),
        migrations.CreateModel(
            name='Document1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Имя')),
                ('document1', models.FileField(upload_to='documents1/')),
            ],
            options={
                'verbose_name': 'Рац предложения',
                'verbose_name_plural': 'Рац предложения',
            },
        ),
        migrations.CreateModel(
            name='Document5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Имя')),
                ('document', models.FileField(upload_to='documents5/')),
            ],
            options={
                'verbose_name': 'Документация',
                'verbose_name_plural': 'Документация',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_filial', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиал',
            },
        ),
        migrations.CreateModel(
            name='GpaModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Модификация ГПА',
                'verbose_name_plural': 'Модификация ГПА',
            },
        ),
        migrations.CreateModel(
            name='GpaNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Номер ГПА',
                'verbose_name_plural': 'Номер ГПА',
            },
        ),
        migrations.CreateModel(
            name='IsNotNecessary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KcNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_ks', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Номер КС',
                'verbose_name_plural': 'Номер КС',
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'МПН',
                'verbose_name_plural': 'МПН',
            },
        ),
        migrations.CreateModel(
            name='Narabotka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refuses', models.IntegerField(max_length=500)),
                ('refuses_kip', models.IntegerField(max_length=500)),
            ],
            options={
                'verbose_name': 'Отказы не приведших к АО',
                'verbose_name_plural': 'Отказы не приведших к АО',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Otkaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lpu', models.CharField(max_length=500, verbose_name='Лпу')),
                ('net', models.IntegerField(max_length=500)),
                ('date', models.DateField(verbose_name='Дата')),
                ('vidotkaza', models.CharField(max_length=500, verbose_name='Лпу')),
            ],
            options={
                'verbose_name': 'Приведшие к АО отказы СА',
                'verbose_name_plural': 'Приведшие к АО отказы СА',
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиция',
            },
        ),
        migrations.CreateModel(
            name='Predicions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_refuses', models.CharField(max_length=500, verbose_name='тип отказа')),
                ('type_gpa', models.CharField(max_length=500, verbose_name='Тип ГПА')),
                ('type_say', models.CharField(max_length=500, verbose_name='Тип САУ')),
                ('type_equioment', models.CharField(max_length=500, verbose_name='Внешнее проявления отказа')),
                ('element', models.CharField(max_length=500, verbose_name='Подробное описание причины отказа')),
                ('refuses_element', models.CharField(max_length=500, verbose_name='Элемента отказа')),
                ('maybe_reasons', models.CharField(max_length=500, verbose_name='Отказавший элемент')),
                ('meropriation', models.CharField(max_length=500, verbose_name='Содержание Мероприятия')),
            ],
            options={
                'verbose_name': 'Экспертная система отказ СА',
                'verbose_name_plural': 'Экспертная система отказ СА',
            },
        ),
        migrations.CreateModel(
            name='SauModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Модификация САУ',
                'verbose_name_plural': 'Модификация САУ',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ks', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станция',
            },
        ),
        migrations.CreateModel(
            name='Vnerdenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lpu', models.CharField(max_length=500, verbose_name='Лпу')),
                ('department', models.CharField(max_length=500, verbose_name='Цех')),
                ('gpa_number', models.IntegerField(max_length=50, null=True, verbose_name='Номер Гпа')),
                ('ip', models.CharField(max_length=500, verbose_name='Наименование ИП')),
                ('type_equipment', models.CharField(max_length=500, verbose_name='Тип оборудования')),
                ('ip_number', models.CharField(max_length=50, null=True, verbose_name='Номер Ип')),
                ('done', models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=50, null=True, verbose_name='Выполнено')),
                ('reason', models.CharField(blank=True, max_length=50, null=True, verbose_name='Причина не выполнения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Информ письма',
                'verbose_name_plural': 'Информ письма',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Обычный', max_length=20, verbose_name='статус пользователя')),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.event')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.filial', verbose_name='филиал')),
                ('gpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.gpanumber')),
                ('kc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.kcnumber')),
                ('mpn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.mpn')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.plans')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.station')),
            ],
        ),
        migrations.CreateModel(
            name='Kc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.kcnumber')),
            ],
            options={
                'verbose_name': 'КС',
                'verbose_name_plural': 'КС',
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa_number', models.IntegerField(null=True, verbose_name='Номер Гпа')),
                ('date', models.DateField(verbose_name='Дата')),
                ('defects_count', models.IntegerField(verbose_name='Наработка')),
                ('months', models.CharField(max_length=50, verbose_name='месяца')),
                ('fio', models.CharField(max_length=50, verbose_name='ФИО')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.event', verbose_name='Мероприятия')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.filial', verbose_name='Филиал')),
                ('gpa_modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.gpamodification', verbose_name='Модификация ГПА')),
                ('kc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.kcnumber', verbose_name='Кс')),
                ('mpn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.mpn', verbose_name='МПН')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.position', verbose_name='Позиция')),
                ('sau_modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.saumodification', verbose_name='Модификация САУ')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.station', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Наработка СА',
                'verbose_name_plural': 'Наработка СА',
            },
        ),
        migrations.CreateModel(
            name='Even',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=50, null=True, verbose_name='Cтанция')),
                ('department', models.CharField(max_length=500, null=True, verbose_name='Цех')),
                ('gpa_number', models.IntegerField(max_length=50, null=True, verbose_name='Номер Гпа')),
                ('sau_modifications', models.CharField(max_length=100, null=True, verbose_name='Модификация САУ')),
                ('complete', models.IntegerField(blank=True, default=0, max_length=50, null=True, verbose_name='Выполнено')),
                ('plan', models.IntegerField(null=True, verbose_name='План')),
                ('isnotnecessary', models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=15, null=True, verbose_name='Не требуется')),
                ('done', models.IntegerField(blank=True, default=0, max_length=50, null=True, verbose_name='Выполнено')),
                ('text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Примечания')),
                ('cvartal1', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Квартал 1')),
                ('cvartal2', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Квартал 2')),
                ('cvartal3', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Квартал 3')),
                ('cvartal4', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Квартал 4')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='back.category', verbose_name='Категории')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Document3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=500, verbose_name='Ип')),
                ('ip_code', models.CharField(max_length=500, verbose_name='Ип код')),
                ('naim_ip', models.CharField(max_length=500, verbose_name='Наименование Ип')),
                ('type_gpa', models.CharField(max_length=500, verbose_name='Тип Гпа')),
                ('type_equiomentt', models.CharField(max_length=500, verbose_name='Вид оборудование')),
                ('type_equioment', models.CharField(max_length=500, verbose_name='Тип оборудование')),
                ('filial', models.CharField(max_length=500, verbose_name='Тип филиал')),
                ('date', models.DateField(verbose_name='Дата')),
                ('document3', models.FileField(upload_to='documents3/')),
                ('text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Примечания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Реестр ИП',
                'verbose_name_plural': 'Реестр ИП',
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lpu', models.CharField(max_length=500, verbose_name='Лпу')),
                ('station', models.CharField(max_length=50, null=True, verbose_name='Кс')),
                ('department', models.CharField(max_length=500, verbose_name='Цех')),
                ('gpa_number', models.IntegerField(max_length=50, null=True, verbose_name='Номер Гпа')),
                ('gpa_typle', models.CharField(max_length=100, null=True, verbose_name='Тип Гпа')),
                ('sau_modifications', models.CharField(max_length=100, null=True, verbose_name='Модификация САУ')),
                ('type_equioment', models.CharField(max_length=500, verbose_name='Тип оборудование')),
                ('ip', models.CharField(max_length=500, verbose_name='Ип')),
                ('n_ip', models.CharField(max_length=500, verbose_name='Наименование Ип')),
                ('data_complete', models.CharField(max_length=200, verbose_name='дата выполнения')),
                ('complete', models.CharField(blank=True, choices=[('Да', 'Да')], max_length=50, null=True, verbose_name='Выполнено')),
                ('text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Примечания')),
                ('category5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='back.category5', verbose_name='выполнено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Контроль внедрения',
                'verbose_name_plural': 'Контроль внедрения',
            },
        ),
    ]
